Repository bieniu/ha-shellies-discovery, pull requests merged in 2023-02, with the labels that each got.

#371 Allow updating dimmer brightness when lamp is off
  python_scripts/shellies_discovery.py
Labels: new-feature

#379 Use ruff linter
  .flake8
  .github/workflows/lint.yml
  .github/workflows/pre-commit-update.yml
  .pre-commit-config.yaml
  LICENSE
  python_scripts/shellies_discovery.py
  requirements-test.txt
  ruff.toml
Labels: ci

#380 Support OFF mode and add automatic temperature control sensor for TRV
  README.md
  info.md
  python_scripts/shellies_discovery.py
Labels: new-feature

#381 Use `suggested_display_precision` instead of rounding value
  hacs.json
  python_scripts/shellies_discovery.py
Labels: new-feature

#385 Improve templates
  python_scripts/shellies_discovery.py
Labels: new-feature

#387 Remove Wh -> kWh conversion and `use_kwh` option
  README.md
  info.md
  python_scripts/shellies_discovery.py
Labels: breaking-change

#388 Avoid Gen2 announce payloads
  README.md
  info.md
Labels: new-feature
